8888

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,15 +27,15 @@ jobs:
           "
 
       - name: List downloaded backup files
-        run: ls -R ./backup/${{ env.BACKUP_FOLDER }}
+        run: ls -R ./
 
 
       - name: Upload backup to FTP server as dated backup folder
         run: |
           lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
             set ssl:verify-certificate no;
-            mkdir -p /backup/${{ env.BACKUP_FOLDER }} || { echo 'Cannot create backup folder, skipping backup' && exit 0; }
-            mirror --reverse --verbose ./backup/${{ env.BACKUP_FOLDER }} /backup/${{ env.BACKUP_FOLDER }};
+            mkdir -p ./backup/${{ env.BACKUP_FOLDER }} || { echo 'Cannot create backup folder, skipping backup' && exit 0; }
+            mirror --reverse --verbose ./backup/${{ env.BACKUP_FOLDER }} ./backup/${{ env.BACKUP_FOLDER }};
             bye
           "
 
