222

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,7 +22,7 @@ jobs:
         run: |
           lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
             set ssl:verify-certificate no;            
-            mirror --verbose --exclude-glob ./pub/backup_* /pub ./${{ env.BACKUP_FOLDER }};
+            mirror --verbose --exclude-glob backup /pub ./backup/${{ env.BACKUP_FOLDER }};
             bye
           "
 
@@ -30,8 +30,8 @@ jobs:
         run: |
           lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
             set ssl:verify-certificate no;
-            mkdir -p /pub/${{ env.BACKUP_FOLDER }} || { echo 'Cannot create backup folder, skipping backup' && exit 0; }
-            mirror --reverse --verbose --exclude-glob ./pub/backup_* ./${{ env.BACKUP_FOLDER }} /pub/${{ env.BACKUP_FOLDER }};
+            mkdir -p /pub/backup/${{ env.BACKUP_FOLDER }} || { echo 'Cannot create backup folder, skipping backup' && exit 0; }
+            mirror --reverse --verbose ./backup/${{ env.BACKUP_FOLDER }} /pub/backup/${{ env.BACKUP_FOLDER }};
             bye
           "
 
