Refactor backup process in main.yml to streamline folder creation and permissions handling

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,37 +12,44 @@ jobs:
 
       - name: Install lftp
         run: sudo apt-get install lftp
-
-      # - name: List all directories in root folder of FTP server
-      #   run: |
-      #     lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
-      #       set ssl:verify-certificate no;
-      #       cls -l;
-      #       bye
-      #     "
+      
 
       - name: Set backup folder name with date
         id: set_backup
         run: echo "BACKUP_FOLDER=backup_$(date +'%Y%m%d')" >> $GITHUB_ENV
 
-      - name: Backup existing /pub folder on FTP server to /backup_YYYYMMDD, excluding backup folders
+      # - name: Backup existing /pub folder on FTP server to /backup_YYYYMMDD, excluding backup folders
+      #   run: |
+      #     lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
+      #       set ssl:verify-certificate no;
+      #       mkdir -p /pub || echo 'Directory /pub already exists or cannot be created';
+      #       mkdir -p /pub/${{ env.BACKUP_FOLDER }} || { echo 'Cannot create backup folder, skipping backup' && exit 0; }
+      #       site chmod 777 /pub;
+      #       site chmod 777 /pub/${{ env.BACKUP_FOLDER }};
+      #       bye
+      #     " 
+
+      # - name: Mirror /pub to backup folder, excluding backup folders
+      #   run: |
+      #     lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
+      #       set ssl:verify-certificate no;
+      #       mirror --verbose --exclude-glob pub/backup_* /pub /pub/${{ env.BACKUP_FOLDER }};
+      #       bye
+      #     "
+      
+      - name: Download /pub folder from FTP server to runner
         run: |
           lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
             set ssl:verify-certificate no;
-            mkdir -p /pub || echo 'Directory /pub already exists or cannot be created';
-            mkdir -p /pub/${{ env.BACKUP_FOLDER }} || { echo 'Cannot create backup folder, skipping backup' && exit 0; }
-            site chmod 777 /pub;
-            site chmod 777 /pub/${{ env.BACKUP_FOLDER }};
+            mirror --verbose --exclude-glob pub/backup_* /pub ./pub_backup;
             bye
           "
-      - name: Wait for backup folder creation
-        run: sleep 10
 
-      - name: Mirror /pub to backup folder, excluding backup folders
+      - name: Upload backup to FTP server as dated backup folder
         run: |
           lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
             set ssl:verify-certificate no;
-            mirror --verbose --exclude-glob pub/backup_* /pub /pub/${{ env.BACKUP_FOLDER }};
+            mirror --reverse --verbose ./pub_backup /pub/${{ env.BACKUP_FOLDER }};
             bye
           "
 
