Fix backup folder permissions and ensure its creation in the upload step

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -36,11 +36,11 @@ jobs:
       #       mirror --verbose --exclude-glob pub/backup_* /pub /pub/${{ env.BACKUP_FOLDER }};
       #       bye
       #     "
-      
+
       - name: Download /pub folder from FTP server to runner
         run: |
           lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
-            set ssl:verify-certificate no;
+            set ssl:verify-certificate no;            
             mirror --verbose --exclude-glob pub/backup_* /pub ./pub_backup;
             bye
           "
@@ -49,6 +49,8 @@ jobs:
         run: |
           lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }} -e "
             set ssl:verify-certificate no;
+            mkdir -p /pub/${{ env.BACKUP_FOLDER }} || { echo 'Cannot create backup folder, skipping backup' && exit 0; }
+            chmod 777 /pub/${{ env.BACKUP_FOLDER }};
             mirror --reverse --verbose ./pub_backup /pub/${{ env.BACKUP_FOLDER }};
             bye
           "
